solr/core/src/java/org/apache/solr/cloud/RecoveryStrategy.java, solr/core/src/java/org/apache/solr/handler/IndexFetcher.java, solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java
This avoid commits calls to leader for Pull replicas and also avoid recreating the core repeatedly when the leader has no data
=> Adding improvements to pull replica efficiency

solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
This PR adds a warn log to the SearchHandler when an Exception is encountered during a ShardRequest.
=> Extra logging in SearchHandler [sc-214651] 

solr/core/src/java/org/apache/solr/cloud/ZkController.java, solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/test/org/apache/solr/core/SolrCoreConfigTest.java
This PR ports the system property `disable.zk.config.watch` to Solr 9.
[[sc-214578]](https://app.shortcut.com/fullstory/story/214578/add-java-system-property-to-disable-config-watch)
=> Add java system property to disable config watch 

solr/core/src/java/org/apache/solr/cloud/Overseer.java
This PR adds a Java system property for overseer queue size. 
Note: the null pointer exception fix was not included in this PR since it was fixed in this Solr upstream PR: [SOLR-15146](https://github.com/cowpaths/fullstory-solr/commit/4a78b458047c8803aed583d0d17ec6017d72b766#diff-45a542ca16eb58266f1bf2774184fbcb9713011e10d3126010cdf8529d6059ec)
=> Add java system property to overseer queue size

solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java, solr/server/resources/log4j2.xml
Apply changes from https://github.com/fullstorydev/lucene-solr/pull/102
Apply changes for the above branch, details:
Changes included in this PR:
1. Add log marker based on path (upstreamed in https://issues.apache.org/jira/browse/SOLR-16582)
2. Add info message on search start (not upstreamed, see discussions in https://github.com/apache/solr/pull/1237 https://issues.apache.org/jira/browse/SOLR-16586)
3. Simplified message on sub-shard requests -(not upstreamed as this is quite specific to FS usage. Solr community might not like the fact that full query is no longer printed for handler processing in the data node - for us it's okay as it's easy for us to see ALL logs across nodes including QA node from BQ)
4.  Enable handling of rid from external systems - (not upstreamed, Solr is using …
=> sc 214640 : log cleanup and req tracing [from lucene-solr]

solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginIntegrationTest.java
This PR: https://github.com/cowpaths/fullstory-solr/pull/46 seems to have removed indentation for the JSON used in these tests as well. This isn't an issue in terms of functionality but if broke the comparison in the test. This change removes indentation from the expected JSON to fix these tests.
=> Fixing the JWTAuthPluginIntegrationTest by removing indentation in expected JSON

solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java, solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
See also:
1. https://github.com/fullstorydev/lucene-solr/commit/445508adb4a
2. https://issues.apache.org/jira/browse/SOLR-16099
3. https://issues.apache.org/jira/browse/SOLR-16129
To be clear, I haven't tried to evaluate whether this works in practice. Request-sending logic changed considerably as of SOLR-14354, so this wasn't a straight cherry-pick of https://github.com/fullstorydev/lucene-solr/commit/445508adb4a. Following on conversation with Patson though, it sounds like we are seeing these messages logged in staging, so hopefully we can iterate on this if necessary.
=> add detection/logging of http2 delay in intra-cluster request sending

solr/core/src/java/org/apache/solr/handler/export/ExportWriter.java, solr/core/src/test/org/apache/solr/handler/export/TestExportWriter.java
Currently the Solr stream and export handlers are not able to use glob patterns for fields, similar to how we can for the select handler. For example, passing `fl=*` or `fl=*_bool` to the export handler will not work.
In order to be able to use the export handler with a schema having dynamic fields, we will need the ability to support glob patterns. This implementation finds fields in the schema that match the given pattern and only includes them for export if they are both `docValues=true` and `useDocValuesAsStored=true`, otherwise they are skipped.
=> Adding ability to get fields via glob patterns for export handler

solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java, solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java, solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java, solr/solrj/src/test/org/apache/solr/common/cloud/PerReplicaStatesIntegrationTest.java
https://fullstory.atlassian.net/browse/SAI-4421
It's found during benchmarking that solr-bench failed to restart Solr due to replicas not marked as leader/active from the cluster api call for PRS enabled collections.
This only happens in 9.2
it appears that removing the readPrs() call in this change [SOLR-16580: Avoid making copies of DocCollection for PRS updates (#1242) · cowpaths/fullstory-solr@c4f4023](https://github.com/cowpaths/fullstory-solr/commit/c4f40233a718d60262ffc2610a02dfccdde7f641#diff-3cf27848269b8f72d6270cb4e36892fd67a270ea09d1531e97a48ad7c8355419L154)  stopped putting “leader” and “status” info from the replica state into the propMap of Replica. Such propMap is essential as the ClusterStatus handler has some pretty odd logic here [fullstory-solr/ClusterStatus.java at …
=> SAI-4421: Fix for missing attributes from cluster api call for PRS collection in 9.2

solr/bin/solr
Quick update PR to #94, this allows running Solr HTTPS on ports other than `8983`. Before, if you set `-p 28983`, `SOLR_SSL_PORT` would still default to `8983`. If you're intending to start an HTTPS server, this is confusing, since `-p` only sets `SOLR_PORT` and not `SOLR_SSL_PORT`. Setting it here instead of in the `-p` switch case allows the user to set  `SOLR_SSL_PORT` via env.
=> default SOLR_SSL_PORT to SOLR_PORT

solr/core/src/java/org/apache/solr/handler/UpdateRequestHandler.java, solr/core/src/test/org/apache/solr/core/RequestHandlersTest.java
There is a unit test case failure after change in #95 
https://github.com/cowpaths/fullstory-solr/actions/runs/4881276600/jobs/8709971562?pr=98
For non cloud based update request, the code logic would identify as isDistrib = false, hence incrementing the `update[local]` metrics instead of the expected `update` metrics in the unit test case
Using `distrib=false` in specific to our FS client https://github.com/cowpaths/mn/blob/6b6148200d1fdf416ed7a00e04888d5b9dbd64de/projects/fullstory/go/src/fs/solr/solrcloud/client.go#L427  (in fact from code search and debugging, distrib does not affect the update flow)
In order to keep the existing behavior we will ONLY send the update requests with explicit `distrib=false` to our "local" update metrics, and everything else should just fall into the …
=> Fixed unit test case failure due to metric changes

solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java, solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/PerReplicaStatesFetcher.java, solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java, solr/solrj/src/java/org/apache/solr/common/util/CommonTestInjection.java
This is just a cherry pick of commits from https://github.com/apache/solr/pull/1460
Detailed described in the above link
We are creating this PR as we want such change in our own repo (ran into that occasionally on playpen eu1 c91) as the upstream change is still under review
This same was reviewed for 8.8 as in https://github.com/fullstorydev/lucene-solr/pull/210
=> SAI-4358 : PRS collection deletion race condition

solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java
Found unit test case error as in https://github.com/cowpaths/fullstory-solr/actions/runs/5074467211/attempts/1
This is due to the cherry pick missed the fact that the `/beforePrsFetch` breakpoint is now placed in `PerReplicaStateFetcher` instead of `ZkStateReader` therefore subsequent tests could still trigger the breakpoint as the cleanup had incorrect name (ie this label https://github.com/cowpaths/fullstory-solr/pull/103/files#diff-c92a116c89a724226fb6efbea4c4f90ab70b40a779e1c50155c8eca646520358R750 did not match this https://github.com/cowpaths/fullstory-solr/pull/103/files#diff-c92a116c89a724226fb6efbea4c4f90ab70b40a779e1c50155c8eca646520358R789 )
=> SAI-4358: Fixed breakpoint cleanup in unit test case

solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/CloudSolrStream.java, solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/expr/StreamExpressionNamedParameter.java, solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/expr/StreamExpressionParser.java, solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamDecoratorTest.java, solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionToExpessionTest.java, solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/expr/StreamExpressionParserTest.java
This uses a regular expression with lookbehind to replace only `:\"` with `:"` and applicable end quote to ensure that we still can handle queries like `fieldA:\"someterms\"` but also handle `fieldA:"some\"terms"`.
The regular expression approach is probably not the most performant, but it is relatively simple and we could explore in the future getting streaming expression parsing more in sync with parsing of normal queries.
=> Updating streaming parser to better handle nested quotes

solr/core/src/java/org/apache/solr/cluster/placement/plugins/SimplePlacementFactory.java
We experienced solr replica placement concentration on C91 for node 100-103 while we "pre-shard" c91 (that adds empty collections to C91 with certain shard count)
In Solr 8, the core on other collections [are counted correctly ](https://github.com/fullstorydev/lucene-solr/blob/release/8.8/solr/core/src/java/org/apache/solr/cloud/api/collections/Assign.java#L444), while in Solr 9, the logic [here](https://github.com/cowpaths/fullstory-solr/blob/fs/branch_9x/solr/core/src/java/org/apache/solr/cluster/placement/plugins/SimplePlacementFactory.java#L134) adds the replica to the map but does not increment the totalReplicas field, which is probably a bug
Always call `ReplicaCount#addReplica` for all counting cases:
1. Counting existing replicas for all nodes
2. Adding an extra replica to the …
=> SAI-4525 : Simple placement plugin does not work as intended

solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
It's found in Solr 9 that rid is not longer printed in the log:
`2023-06-29 16:37:16.415 INFO (qtp315072539-4821603) [c:174G8N s:shard8 r:core_node37 x:174G8N_shard8_replica_n9 rid:-140545029] o.a.s.h.c.SearchHandler Start External Search Query: distrib=false&indent=off&ids=1ehpolbvvgg!1u59sgp3400_6mt4c25hd2k7_swztpmxsqakh_0&ids=1ehpolbvvgg!1u59sgp3400_6mt4c25hd2k7_swztpmxsqakh&ids=1ehpolbvvgg!1u59sgp3400_6mt4c25hd2k7&ids=1ehpolbvvgg!_&ids=1ehpolbvvgg!1u59sgp3400&wat=&wt=json`
####Solr 9
`2023-06-29 16:38:15.320 INFO (qtp2083217543-60870) [10VQQM shard4 core_node14 10VQQM_shard4_replica_n13 ] o.a.s.h.c.SearchHandler Start External Search Query: distrib=false&indent=off&ids=1r8u3smrj7k!1h90us13ojk_1lisn4m8x6o_bdrh46lya923_0&ids=1r8u3smrj7k!1h90us13ojk_1lisn4m8x6o_bdrh46lya923&ids=1r8u3smrj7 …
=> SAI-4528 : Missing rid in `SearchHandler` log

solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java, solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/java/org/apache/solr/schema/BloomStrField.java, solr/modules/analytics/src/java/org/apache/solr/handler/AnalyticsHandler.java
This lays the groundwork for (at least temporarily) being able to disable special ngram handling, for performance impact evaluation and possible quick rollback if necessary.
=> support dynamic ngram disable (after pattern of SolrQueryTimeoutImpl)

solr/core/src/java/org/apache/solr/query/DynamicComplementPrefixQuery.java
=> DynamicComplementPrefixQuery: we must explicitly check for limitLength < 0 or we may get NPE

solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
This is a bit of a hack, but has a huge impact on latency (reducing for some requests by ~100x). Co-dependent on a corresponding change in UpdateRequestProcessor.
=> SAI-4620: (FS-specific) pre-filter dynamic docValues fields for field value retrieval

solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/test/org/apache/solr/handler/component/SearchHandlerTest.java, solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
These exceptions for non-distributed requests seem to be exclusively issues with invalid queries, such as Surround queries that exceed the max number of basic queries.
https://github.com/cowpaths/lucene/blob/2cbf261032dc8aca56c846971c090c991ac594a6/lucene/queryparser/src/java/org/apache/lucene/queryparser/surround/query/TooManyBasicQueries.java
=> Handling Query Parsing Exceptions from Lucene queries

solr/core/src/test/org/apache/solr/jersey/PostRequestLoggingFilterTest.java
This is a followup to #131, I think? Test fails reliably; e.g.:
```
gradlew :solr:core:test --tests "org.apache.solr.jersey.PostRequestLoggingFilterTest.testRequestBodyRepresentedAsJsonWhenFound" -Ptests.jvms=5 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:ReservedCodeCacheSize=120m" -Ptests.seed=3607EC61D430207E -Ptests.file.encoding=US-ASCII
```
=> indentation test fix

solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java, solr/core/src/java/org/apache/solr/handler/component/ShardResponse.java, solr/core/src/test/org/apache/solr/handler/component/SearchHandlerTest.java
This will ensure that distributed requests are considered failing requests if any shard fails with a BAD_REQUEST (400) error indicating that that request is not something that can just succeed on retry.
=> Handling BAD_REQUEST exceptions as failures even with shard.tolerant as true

solr/core/src/java/org/apache/solr/core/SolrConfig.java, solr/core/src/java/org/apache/solr/index/SlowCompositeReaderWrapper.java, solr/core/src/java/org/apache/solr/search/CaffeineCache.java, solr/core/src/java/org/apache/solr/search/OrdMapRegenerator.java, solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java, solr/core/src/java/org/apache/solr/search/facet/UnInvertedField.java, solr/core/src/java/org/apache/solr/search/function/OrdFieldSource.java, solr/core/src/java/org/apache/solr/search/function/ReverseOrdFieldSource.java, solr/core/src/java/org/apache/solr/update/VersionInfo.java, solr/core/src/test/org/apache/solr/index/TestSlowCompositeReaderWrapper.java, solr/core/src/test/org/apache/solr/schema/TestPointFields.java, solr/core/src/test/org/apache/solr/search/TestOrdMapCache.java, solr/core/src/test/org/apache/solr/uninverting/TestDocTermOrds.java, solr/core/src/test/org/apache/solr/uninverting/TestDocTermOrdsUninvertLimit.java, solr/core/src/test/org/apache/solr/uninverting/TestFieldCache.java, solr/core/src/test/org/apache/solr/uninverting/TestFieldCacheVsDocValues.java, solr/core/src/test/org/apache/solr/uninverting/TestLegacyFieldCache.java, solr/core/src/test/org/apache/solr/uninverting/TestUninvertingReader.java, solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
building on recent upstream work that stores OrdinalMaps in a ConcurrentHashMap, here we make OrdinalMap caching configurable within the standard Solr caching framework. This allows, e.g., OrdinalMap caches to be directly warmed, etc...
A couple of things to note:
1. technicality: `fs/branch_9x` upon which this is based seems currently to be failing, so we should merge from `fs/branch_9x` after merging cowpaths/fullstory-solr#118 to get meaningful CI results for this PR. EDIT: DONE
2. We will likely want to rework this PR to incorporate changes from https://github.com/apache/solr/pull/1351, for cleaner configuration of node-level caches. Notes about some affected workarounds are left in detailed portions of commit messages.
=> introduce first-class cache for OrdinalMaps

solr/core/src/java/org/apache/solr/core/SolrCore.java, solr/core/src/java/org/apache/solr/update/UpdateLog.java, solr/core/src/test/org/apache/solr/cloud/TestCloudRecovery.java, solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java, solr/core/src/test/org/apache/solr/cloud/TestTlogReplica.java, solr/core/src/test/org/apache/solr/update/CustomTLogDirTest.java
This presents an alternative fix to that proposed in #130. I think I've tracked this bug down to a series of commits between 2012-2015, which corrupted the initial intended behavior. This PR attempts to restore the original intent.
No tests yet, but this really needs tests.
=> an alternate approach to fixing tlog dir handling

solr/core/src/java/org/apache/solr/cloud/ActiveReplicaWatcher.java, solr/core/src/java/org/apache/solr/cloud/ZkController.java, solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java, solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
No tests yet; will be tricky to test this, esp because I'm not 100% sure where the race condition actually comes in. _Buuut_ I can definitely see several opportunities for race conditions, and this PR will fix the issue by leaning on the deduplication of `collectionWatches` and slightly modifying the logic of how StateWatcher determines whether to expire or reset the watch.
=> SAI-4661: fix race condition in singleton-per-collection StateWatcher creation
