solr/core/src/java/org/apache/solr/core/SolrConfig.java
solr/core/src/java/org/apache/solr/core/SolrCore.java
solr/core/src/java/org/apache/solr/search/facet/FacetHeatmap.java
solr/core/src/java/org/apache/solr/search/facet/FacetModule.java
solr/core/src/java/org/apache/solr/search/facet/FacetParser.java
solr/core/src/java/org/apache/solr/search/facet/FacetParserFactory.java
solr/core/src/java/org/apache/solr/search/facet/FacetProcessor.java
solr/core/src/java/org/apache/solr/search/facet/FacetRangeParser.java
solr/core/src/java/org/apache/solr/search/facet/SlotAcc.java

https://github.com/cowpaths/solr/pull/1
https://issues.apache.org/jira/browse/SOLR-XXXXX
Please provide a short description of the changes you're making with this pull request.
Please provide a short description of the approach taken to implement your solution.
Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.
Please review the following and check all that apply:

merging facet parser factory into release/9x

---

.gitignore
.gitmodules

https://issues.apache.org/jira/browse/SOLR-XXXXX
Please provide a short description of the changes you're making with this pull request.
Please provide a short description of the approach taken to implement your solution.
Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.
Please review the following and check all that apply:

Added lucene sub module

---

solr/core/src/java/org/apache/solr/search/CacheConfig.java
solr/core/src/java/org/apache/solr/search/CaffeineCache.java
solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
solr/core/src/java/org/apache/solr/servlet/PrometheusMetricsServlet.java
solr/core/src/test/org/apache/solr/servlet/PrometheusMetricsServletTest.java
solr/webapp/web/WEB-INF/web.xml

Feature prometheus servlet, which exposes solr metrics in prometheus format  

---

solr/core/src/java/org/apache/solr/core/SolrConfig.java
solr/core/src/java/org/apache/solr/core/SolrCore.java
solr/core/src/java/org/apache/solr/search/facet/FacetHeatmap.java
solr/core/src/java/org/apache/solr/search/facet/FacetModule.java
solr/core/src/java/org/apache/solr/search/facet/FacetParser.java
solr/core/src/java/org/apache/solr/search/facet/FacetParserFactory.java
solr/core/src/java/org/apache/solr/search/facet/FacetProcessor.java
solr/core/src/java/org/apache/solr/search/facet/FacetRangeParser.java
solr/core/src/java/org/apache/solr/search/facet/SlotAcc.java

Add facet parser factories and plugin support to solr 9.0

---

solr/core/src/java/org/apache/solr/search/ValueSourceParser.java
solr/core/src/java/org/apache/solr/search/facet/HLLAgg.java

Added support for HLL params. (#113)

---

.github/workflows/gradle-precommit.yml
.gitignore
.gitmodules

Added lucene submodule pointing lucene fs/branch_9_4_1

---

solr/core/src/java/org/apache/solr/search/ValueSourceParser.java
solr/core/src/java/org/apache/solr/search/facet/PercentileAgg.java
solr/core/src/test/org/apache/solr/search/facet/TestJsonFacets.java

Bump tdigest for latest updates and add a percentile configurable

---

solr/core/src/java/org/apache/solr/core/SolrConfig.java

Added FacetParserFactory to staticlist - bug fix

---

solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java

cherry-pick from `fs/branch_9x`

Extra logging in SearchHandler [sc-214651]

---

solr/core/src/java/org/apache/solr/cloud/Overseer.java

cherry-pick from `fs/branch_9x`

Add java system property to overseer queue size (#43)

---

solr/core/src/java/org/apache/solr/core/NodeConfig.java
solr/core/src/test/org/apache/solr/core/TestCoreContainer.java

cherry pick from solr main https://github.com/apache/solr/commit/fba08f4361b

SOLR-16553: solr.install.dir property not initialized

---

.github/workflows/gradle-precommit.yml
.github/workflows/solr-test.yml

I tried just with just solrj and core tests and running all tests takes just about as much time so might as well run them all.
At this point I'm keeping the test job as not being required for merge since we have some intermittent test failures at times.

Adding solr tests to precommit checks

---

solr/core/src/java/org/apache/solr/cloud/Overseer.java
solr/core/src/java/org/apache/solr/cloud/overseer/ZkStateWriter.java
solr/core/src/java/org/apache/solr/core/CloudConfig.java
solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java
solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateWriterTest.java
solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZkClient.java
solr/solrj/src/java/org/apache/solr/common/util/CompressionUtil.java
solr/solrj/src/test/org/apache/solr/common/cloud/SolrZkClientCompressedDataTest.java
solr/solrj/src/test/org/apache/solr/common/util/CompressionUtilTest.java

This is just a cherry pick of https://github.com/cowpaths/fullstory-solr/pull/47

Ability to compress the collection state [sc-214780] (#47)

---

solr/solrj/src/java/org/apache/solr/common/util/Utils.java
solr/solrj/src/test/org/apache/solr/common/cloud/DocCollectionTest.java

* Changed indent size for state.json file from 2 to 0
* updated test. Set default indent to 0
https://issues.apache.org/jira/browse/SOLR-XXXXX
Please provide a short description of the changes you're making with this pull request.
Please provide a short description of the approach taken to implement your solution.
Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.
Please review the following and check all that apply:

SOLR-16448: Set default indent size to 0 for json serilization

---

solr/core/src/java/org/apache/solr/search/facet/FacetBucket.java

Shard flag is only needed when a given facet or subfacet has refinement enabled. Do not set the flag otherwise as it has an overflow possibility. Also do not set a bucket num unless refinement is enabled (this also helps with avoiding overflow).
ported https://github.com/fullstorydev/lucene-solr/commit/60fe6ba4a78bde30c374af2dd850dbfcb25ba597

Only set shard flag if refinement is enabled. (#114)

---

solr/core/src/java/org/apache/solr/search/ValueSourceParser.java
solr/core/src/java/org/apache/solr/search/facet/HLLAgg.java
solr/core/src/java/org/apache/solr/search/facet/UniqueAgg.java
solr/core/src/java/org/apache/solr/search/facet/UniqueBlockAgg.java
solr/core/src/java/org/apache/solr/search/facet/UniqueBlockFieldAgg.java
solr/core/src/java/org/apache/solr/search/facet/UniqueBlockQueryAgg.java
solr/core/src/java/org/apache/solr/search/facet/UniqueMultiDvSlotAcc.java
solr/core/src/java/org/apache/solr/search/facet/UniqueMultivaluedSlotAcc.java
solr/core/src/java/org/apache/solr/search/facet/UniqueSinglevaluedSlotAcc.java
solr/core/src/java/org/apache/solr/search/facet/UniqueSlotAcc.java
solr/solr-ref-guide/modules/query-guide/examples/JsonRequestApiTest.java

This comes from https://github.com/fullstorydev/lucene-solr/pull/108.

Port over unique explicit vals flag.

---

solr/core/src/java/org/apache/solr/cloud/ZkController.java

Ported from https://github.com/fullstorydev/lucene-solr/pull/213

Only send downnode message to OS if there's non PRS collection in the node (9.x)

---

solr/core/src/java/org/apache/solr/cloud/ZkController.java

Only send downnode message to OS if there's non PRS collection in the node (9.1)

---

solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java

See https://issues.apache.org/jira/browse/SOLR-16932

make Http2SolrClient max outstanding requests configurable via system property

---

solr/core/src/java/org/apache/solr/query/DynamicComplementPrefixQuery.java

ports further optimization from upstream PR: https://github.com/apache/lucene/pull/12207

direct prefix query need only compare a single index
